# Generated by Django 4.1.7 on 2023-03-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helium10', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketchart',
            name='chart_img',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
